### ISSUE TITLE
Blissify returns reference song in song list

### ISSUE THREAD

**Issue by jcorporation** [Polochon-street/blissify-rs#66]
I discovered this issue as I test the new version, but I think it is not a new issue.

As the title says, blissify returns always the reference song as first song.

Blissify call and the output:

```
blissify playlist --seed-song --dry-run --from-song Alben/5F_55/I/01.496E_2074_6865_2061_726D_7920_6E6F_77.mp3 10
[2024-07-08T21:30:21Z WARN  blissify] Could not find any MPD_HOST environment variable set. Defaulting to 127.0.0.1.
[2024-07-08T21:30:21Z WARN  blissify] Could not find any MPD_PORT environment variable set. Defaulting to 6600.
/home/juergen/musik/Alben/5F_55/I/01.496E_2074_6865_2061_726D_7920_6E6F_77.mp3
/home/juergen/musik/Alben/The_Klinik/Eat_Your_Heart_Out/8.Those.mp3
/home/juergen/musik/Alben/Pzycho_Bitch/Master_of_Myself/04.Come_Back!.mp3
/home/juergen/musik/Alben/Sonar/Remote_Assault/03.One_Thousand_Lights.mp3
/home/juergen/musik/Alben/Front_Line_Assembly/Echoes/05.Echogenetic_(remix_by_Youth_Code).mp3
/home/juergen/musik/Soundtracks/300 Rise of an Empire/04 - Sparta.mp3
/home/juergen/musik/Alben/Pzycho_Bitch/Eden/06.Big_Lover.mp3
/home/juergen/musik/Alben/Front_Line_Assembly/Excursions 1992-1998/Front Line Assembly - Excursions 1992-1998 - 72 Transmutation - Front Line Assembly.mp3
/home/juergen/musik/Alben/The_Retrosic/Prophecy/03.Raw_(As_We_Are).mp3
/home/juergen/musik/Alben/Front_Line_Assembly/Corroded_Disorder/01.Mutate.mp3
```

**Comment by Polochon-street** [comment]
It is on purpose, since it is easier to have it and have the consumer remove it than the opposite (especially if you start a playlist from several songs).
Would it work for your use case to run
```
blissify playlist --seed-song --dry-run --from-song Alben/5F_55/I/01.496E_2074_6865_2061_726D_7920_6E6F_77.mp3 10 | grep -v Alben/5F_55/I/01.496E_2074_6865_2061_726D_7920_6E6F_77.mp3
```

or something like that? Worst case scenario I could add a flag for not displaying the first song(s) there :)

**Comment by jcorporation** [comment]
Ok, thanks for clarification.

**Comment by jcorporation** [comment]
If its on purpose it should return number of songs requested + the reference song. I would certainly expect that.

**Comment by Polochon-street** [comment]
that makes sense - I'll make the help text more helpful and making things more coherent :)

**Comment by Polochon-street** [comment]
Alright, things are a little bit more coherent now in the help text.
Long story short, what happens conceptually when you generate a playlist from a path for blissify is that you select a song, and you want to make and queue a playlist from that song. Since you selected the song from a path (and didn't use the default that chooses the currently playing song), it also adds the song to the playlist.
The number of song is the number of songs "to queue", which in the case also contains the starting song. You happen to use `--dry-run` and plug it somewhere else so it's a bit more inconvenient for you, but requesting NUMBER_SONGS + 1 should hopefully work just fine :)

**Comment by jcorporation** [comment]
Thanks for clarifying!
